name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        scp -r . $REMOTE_USER@$REMOTE_HOST:/var/www/newai
        ssh $REMOTE_USER@$REMOTE_HOST "cd /var/www/newai && ./deploy.sh"
      shell: bash

    - name: Post Deployment Notification
      if: always()
      run: echo "Deployment complete!"
          WIX_ACCOUNT_ID: ${{ secrets.WIX_ACCOUNT_ID }}
